spring:
  application:
    name: paymentgw

  management:
    endpoints:
      jolokia:
        config:
          debug: true
          agentId: paymentgw
          lookupConfig: true
          validateConfig: true
        enabled: true
      web:
        exposure:
          include: 
            - health
            - info
            - metrics
            - loggers
            - threaddump
            - heapdump
            - jolokia
          
  datasource:
    url: jdbc:postgresql://localhost:5432/ap_admin
    username: ap_admin
    password: ap_secret
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# OpenAPI Swagger configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

